# shellcheck shell=bash
# shellcheck disable=SC2016 # Nix expressions and expected shell text in single quotes
# .dotsteward/stage0.<platform>.env (3.7): the values the pre-Nix stage-0
# bootstrap needs, shell-quoted and sourceable by bash 3.2 (no associative
# arrays, no expansion at source time).
# shellcheck source=tests/nix/instance/helpers.sh
source "$DS_REPO_ROOT/tests/nix/instance/helpers.sh"

# stage0_dump INSTANCE_EXPR PLATFORM: sources the stage-0 file in a clean
# bash and prints every DS_STAGE0_* variable (declare -p).
stage0_dump() {
  local file=$DS_TEST_ROOT/stage0.$2.env
  inst_raw "($1).dotstewardMirrors.\"stage0.$2.env\"" >"$file"
  bash -n "$file" || ds_fail "stage0.$2.env is not valid bash"
  assert_not_contains "$(<"$file")" "declare" "no declare in stage0.$2.env"
  assert_not_contains "$(<"$file")" "$(inst_raw 'builtins.storeDir')" "no store path in stage0.$2.env"
  env -i HOME=/nonexistent-home XDG_STATE_HOME=/nonexistent-state PATH=/nonexistent-bin \
    "$BASH" --norc --noprofile -c 'set -eu; source "$1"; declare -p ${!DS_STAGE0_@}' stage0 "$file"
}

linux=$(stage0_dump example linux)
header=$(inst_raw 'example.dotstewardMirrors."stage0.linux.env"' | sed -n '1,3p')
assert_contains "$header" "# Generated by dotsteward" "header"
assert_contains "$header" "dotsteward sync" "header names the command"

expect_var() {
  assert_contains "$1" "declare -- $2" "$2"
}
expect_array() {
  assert_contains "$1" "declare -a $2" "$2"
}

expect_var "$linux" 'DS_STAGE0_SCHEMA_VERSION="1"'
expect_var "$linux" 'DS_STAGE0_SYSTEM="x86_64-linux"'
expect_var "$linux" 'DS_STAGE0_PLATFORM="linux"'
expect_var "$linux" 'DS_STAGE0_INSTANCE_REMOTE="git@github.com:alice/workstation.git"'
expect_var "$linux" 'DS_STAGE0_STATE_ROOT="\${XDG_STATE_HOME:-~/.local/state}/dotsteward"'
expect_var "$linux" 'DS_STAGE0_LEGACY_ENV="false"'
expect_var "$linux" 'DS_STAGE0_HOST_INPUT="workstation"'
expect_var "$linux" 'DS_STAGE0_VERSIONS_LOCK="versions.lock.json"'
expect_array "$linux" 'DS_STAGE0_PROFILES=([0]="workstation" [1]="fresh")'
expect_array "$linux" 'DS_STAGE0_PROFILE_MODES=([0]="workstation=adopt" [1]="fresh=fresh")'
expect_var "$linux" 'DS_STAGE0_DEFAULT_PROFILE="workstation"'
expect_var "$linux" 'DS_STAGE0_CHECK_PROFILE="workstation"'
expect_var "$linux" 'DS_STAGE0_BOOTSTRAP_PROFILE="fresh"'
expect_var "$linux" 'DS_STAGE0_FAST_PATH_OS_ID="ubuntu"'
expect_var "$linux" 'DS_STAGE0_FAST_PATH_OS_VERSION="24.04"'
expect_var "$linux" 'DS_STAGE0_FAST_PATH_ARCHITECTURE="x86_64"'
expect_var "$linux" 'DS_STAGE0_FAST_PATH_DESKTOP_CONTAINS="example"'
expect_array "$linux" 'DS_STAGE0_FAST_PATH_DETECTORS=([0]="example_detector")'
expect_array "$linux" 'DS_STAGE0_DETECTORS=([0]="example_detector")'
expect_array "$linux" 'DS_STAGE0_DETECTOR_0_ARGV=([0]="example-app" [1]="detect")'
expect_var "$linux" "DS_STAGE0_DETECTOR_0_MATCH_LINE=\"it's here\""
expect_array "$linux" 'DS_STAGE0_SNAPSHOTS=([0]="example-app-state")'
expect_array "$linux" 'DS_STAGE0_SNAPSHOT_0_ARGV=([0]="example-app" [1]="dump state")'
expect_var "$linux" 'DS_STAGE0_SNAPSHOT_0_REQUIRE_COMMAND="example-app"'
expect_array "$linux" 'DS_STAGE0_PREREQUISITES_APT=([0]="example-app-deps")'
# Lock paths of the Nix pin and their values (stage-0 runs without jq).
expect_var "$linux" 'DS_STAGE0_NIX_VERSION_AT="nix.version"'
expect_var "$linux" 'DS_STAGE0_NIX_INSTALLER_URL_AT="nix.installer_url"'
expect_var "$linux" 'DS_STAGE0_NIX_INSTALLER_SIZE_AT="nix.installer_size"'
expect_var "$linux" 'DS_STAGE0_NIX_INSTALLER_SHA256_AT="nix.installer_sha256"'
expect_var "$linux" 'DS_STAGE0_NIX_VERSION="2.35.2"'
expect_var "$linux" 'DS_STAGE0_NIX_INSTALLER_URL="https://releases.example.invalid/nix/nix-2.35.2/install"'
expect_var "$linux" 'DS_STAGE0_NIX_INSTALLER_SIZE="4499"'
expect_var "$linux" 'DS_STAGE0_NIX_INSTALLER_SHA256="99d0ddf3c86a252730207c4cf7d2fafaca9f76d14bb98ef588307da33e264d84"'

# Backup paths: core and component bootstrap.backupPaths, then the settings
# targets with at least one buffer entry and backup = true (a buffer target
# replaces a component target of the same name) and every file entry path;
# "~" stays literal.
expect_array "$linux" 'DS_STAGE0_BACKUP_PATHS=([0]="~/.config/nix/nix.conf" [1]="~/.agents/skills" [2]="~/.config/example-app/state" [3]="~/.config/example-app/settings.json" [4]="~/.config/example-extra/settings.toml" [5]="~/.local/bin/example-script.sh")'

# No other variable exists on Linux.
assert_eq 34 "$(grep -c '^declare' <<<"$linux")" "number of linux variables"

# darwin: its fast path and per-platform paths.
darwin=$(stage0_dump example darwin)
expect_var "$darwin" 'DS_STAGE0_SYSTEM="aarch64-darwin"'
expect_var "$darwin" 'DS_STAGE0_PLATFORM="darwin"'
expect_var "$darwin" 'DS_STAGE0_FAST_PATH_MIN_VERSION="14"'
expect_var "$darwin" 'DS_STAGE0_FAST_PATH_ARCHITECTURE="arm64"'
assert_not_contains "$darwin" "DS_STAGE0_FAST_PATH_OS_ID" "no Linux fast path on darwin"
expect_array "$darwin" 'DS_STAGE0_BACKUP_PATHS=([0]="~/.config/nix/nix.conf" [1]="~/.agents/skills" [2]="~/.config/example-app/state" [3]="~/.config/example-app/settings.json" [4]="~/Library/Application Support/example-extra/settings.toml" [5]="~/.local/bin/example-script.sh")'

# The minimal instance: core only, empty lists, defaults.
minimal=$(stage0_dump minimal linux)
expect_array "$minimal" 'DS_STAGE0_PROFILES=([0]="workstation")'
expect_array "$minimal" 'DS_STAGE0_PROFILE_MODES=([0]="workstation=fresh")'
expect_var "$minimal" 'DS_STAGE0_BOOTSTRAP_PROFILE="workstation"'
expect_var "$minimal" 'DS_STAGE0_HOST_INPUT="instance"'
expect_var "$minimal" 'DS_STAGE0_FAST_PATH_DESKTOP_CONTAINS=""'
expect_array "$minimal" 'DS_STAGE0_FAST_PATH_DETECTORS=()'
expect_array "$minimal" 'DS_STAGE0_DETECTORS=()'
expect_array "$minimal" 'DS_STAGE0_SNAPSHOTS=()'
expect_array "$minimal" 'DS_STAGE0_PREREQUISITES_APT=()'
expect_array "$minimal" 'DS_STAGE0_BACKUP_PATHS=([0]="~/.config/nix/nix.conf" [1]="~/.agents/skills")'

# An instance without a settings buffer has no buffer-derived paths.
copy=$(instance_copy "$nix_instance_fixtures/example")
rm -r "$copy/local-maintained-files"
assert_inst_eq '["~/.config/nix/nix.conf","~/.agents/skills","~/.config/example-app/state"]' \
  "(instance { root = /. + \"$copy\"; }).dotstewardManifest.x86_64-linux.backup_paths" "manifest backup paths"
nobuffer=$(stage0_dump "instance { root = /. + \"$copy\"; }" linux)
expect_array "$nobuffer" 'DS_STAGE0_BACKUP_PATHS=([0]="~/.config/nix/nix.conf" [1]="~/.agents/skills" [2]="~/.config/example-app/state")'

# [settings] buffer_dir moves the buffer.
copy=$(instance_copy "$nix_instance_fixtures/example")
mv "$copy/local-maintained-files" "$copy/settings-buffer"
printf '\n[settings]\nbuffer_dir = "settings-buffer"\n' >>"$copy/workstation.toml"
moved=$(stage0_dump "instance { root = /. + \"$copy\"; }" linux)
assert_contains "$moved" '[5]="~/.local/bin/example-script.sh"' "buffer_dir"

# An entry naming an unknown target is an error.
copy=$(instance_copy "$nix_instance_fixtures/example")
printf '\n[[entries]]\nid = "X1"\ntarget = "example-nope"\nkey = ["a"]\nvalue = 1\n' \
  >>"$copy/local-maintained-files/buffer.toml"
assert_inst_fails "(instance { root = /. + \"$copy\"; }).dotstewardMirrors.\"stage0.linux.env\"" \
  "dotsteward: local-maintained-files/buffer.toml: entry X1 names unknown target example-nope"

# A lock without the Nix pin cannot render stage-0.
copy=$(instance_copy "$nix_instance_fixtures/example")
jq 'del(.nix.installer_sha256)' "$nix_instance_fixtures/example/versions.lock.json" >"$copy/versions.lock.json"
assert_inst_fails "(instance { root = /. + \"$copy\"; }).dotstewardMirrors.\"stage0.linux.env\"" \
  "dotsteward: versions.lock.json lacks nix.installer_sha256 (required by component core)"
