# shellcheck shell=bash
# shellcheck disable=SC2154 # DS_* variables come from tests/lib/harness.sh
# tools/gen-stage0.sh and template/bootstrap.sh: the template
# is the generated concatenation of the stage-0 body of
# cli/commands/preflight.sh (between its markers) and cli/lib/stage0.sh,
# committed executable; --check fails when it is stale; the result is pre-Nix
# code: bash 3.2 syntax and builtins, BSD-compatible tool options, no jq.

template=$DS_REPO_ROOT/template/bootstrap.sh
[[ -f $template ]] || ds_fail "template/bootstrap.sh is missing"
[[ -x $template ]] || ds_fail "template/bootstrap.sh is not executable"
stage=$(git -C "$DS_REPO_ROOT" ls-files --stage -- template/bootstrap.sh 2>/dev/null) || stage=""
mode=${stage%% *}
if [[ -n $mode ]]; then
  assert_eq 100755 "$mode" "template/bootstrap.sh is committed executable"
fi
assert_eq '#!/usr/bin/env bash' "$(head -n 1 "$template")" "shebang"

# The committed file is current.
assert_exit 0 bash "$DS_REPO_ROOT/tools/gen-stage0.sh" --check
assert_eq "[dotsteward] template/bootstrap.sh is up to date" "$DS_STDOUT"

# Its layout: header, the body without its markers, stage0.sh without the
# first-line directive for ShellCheck, the call of stage0_main.
body=$(sed -n '/^# dotsteward:stage0:begin$/,/^# dotsteward:stage0:end$/{/^# dotsteward:stage0:/d;p}' \
  "$DS_REPO_ROOT/cli/commands/preflight.sh")
[[ -n $body ]] || ds_fail "no stage-0 body in cli/commands/preflight.sh"
library=$(sed '1{/^# shellcheck shell=bash$/d}' "$DS_REPO_ROOT/cli/lib/stage0.sh")
generated=$(<"$template")
assert_contains "$generated" "$body" "the body"
assert_contains "$generated" "$library" "stage0.sh"
assert_not_contains "$generated" "dotsteward:stage0:" "no markers"
assert_contains "$(sed -n '2,12p' "$template")" "Generated by tools/gen-stage0.sh" "header"
assert_eq 'stage0_main "$@"' "$(tail -n 1 "$template")" "last line"
assert_eq 1 "$(grep -c '^set -Eeuo pipefail$' "$template")" "strict mode once"

# --- regeneration in a copy -------------------------------------------------
copy=$DS_TEST_ROOT/copy
mkdir -p "$copy"
cp -R "$DS_REPO_ROOT/cli" "$DS_REPO_ROOT/tools" "$DS_REPO_ROOT/template" "$copy/"
sed -i 's/^preflight_parse() {$/preflight_parse() {\n  : changed/' "$copy/cli/commands/preflight.sh"
assert_exit 1 bash "$copy/tools/gen-stage0.sh" --check --root "$copy"
assert_eq "[dotsteward] ERROR: template/bootstrap.sh is stale; run tools/gen-stage0.sh" "$DS_STDERR"
assert_exit 0 bash "$copy/tools/gen-stage0.sh" --root "$copy"
assert_eq "[dotsteward] wrote template/bootstrap.sh" "$DS_STDOUT"
assert_contains "$(<"$copy/template/bootstrap.sh")" ": changed"
assert_file_mode "$copy/template/bootstrap.sh" 755
assert_exit 0 bash "$copy/tools/gen-stage0.sh" --check --root "$copy"
# A missing file or a lost executable bit is stale too.
chmod 0644 "$copy/template/bootstrap.sh"
assert_exit 1 bash "$copy/tools/gen-stage0.sh" --check --root "$copy"
assert_eq "[dotsteward] ERROR: template/bootstrap.sh is not executable; run tools/gen-stage0.sh" "$DS_STDERR"
assert_exit 0 bash "$copy/tools/gen-stage0.sh" --root "$copy"
assert_file_mode "$copy/template/bootstrap.sh" 755
rm "$copy/template/bootstrap.sh"
assert_exit 1 bash "$copy/tools/gen-stage0.sh" --check --root "$copy"
assert_eq "[dotsteward] ERROR: template/bootstrap.sh is missing; run tools/gen-stage0.sh" "$DS_STDERR"
assert_exit 0 bash "$copy/tools/gen-stage0.sh" --root "$copy"
assert_exit 0 bash "$copy/tools/gen-stage0.sh" --root "$copy"
assert_eq "[dotsteward] template/bootstrap.sh is up to date" "$DS_STDOUT"
# The markers must be there exactly once, in order.
sed -i '/^# dotsteward:stage0:end$/d' "$copy/cli/commands/preflight.sh"
assert_exit 1 bash "$copy/tools/gen-stage0.sh" --root "$copy"
assert_eq "[dotsteward] ERROR: cli/commands/preflight.sh: expected one '# dotsteward:stage0:begin' line followed by one '# dotsteward:stage0:end' line" \
  "$DS_STDERR"
assert_exit 1 bash "$copy/tools/gen-stage0.sh" --bogus
assert_contains "$DS_STDERR" "unknown option: --bogus"

# --- pre-Nix portability ----------------------------------------------------
bash -n "$template"
if [[ -n ${DS_BASH32:-} ]]; then
  "$DS_BASH32" -n "$template"
  assert_contains "$("$DS_BASH32" --version)" "version 3.2" "DS_BASH32 is bash 3.2"
fi
# Code lines only: comments may mention anything.
code=$(sed -e 's/^[[:space:]]*#.*$//' "$template")
forbidden=(
  '(^|[^[:alnum:]_])(mapfile|readarray|coproc)([^[:alnum:]_]|$)|bash 4 builtin'
  'declare[[:space:]]+-[[:alpha:]]*[AnlucLU]|bash 4 declare option'
  'local[[:space:]]+-[[:alpha:]]*[nA]|bash 4 local option'
  '\[\[[[:space:]]+-v[[:space:]]|[[ -v ]] (bash 4.2)'
  '\$\{[^}]*(,,|\^\^|,|\^)\}|case modification (bash 4)'
  '\$\{[^}]*@[QEPAaKkUuL]\}|parameter transformation (bash 4.4)'
  '\$\{[[:alnum:]_]+:[^}]*:-[0-9]+\}|negative substring length (bash 4.2)'
  '\$\{[[:alnum:]_]+\[-[0-9]+\]\}|negative array index (bash 4.3)'
  '&>>|append both streams (bash 4)'
  '\|&|pipe both streams (bash 4)'
  ';;&|;&|case fall-through (bash 4)'
  '(^|[^[:alnum:]_])wait[[:space:]]+-n|wait -n (bash 4.3)'
  'EPOCHSECONDS|EPOCHREALTIME|BASH_ARGV0|bash 5 variable'
  "printf[[:space:]]+'%\\(|printf time format (bash 4.2)"
  '(^|[^[:alnum:]_])readlink[[:space:]]+-[[:alpha:]]*[fem]|GNU readlink option'
  '(^|[^[:alnum:]_])realpath([^[:alnum:]_]|$)|not on macOS before 13'
  '(^|[^[:alnum:]_])sed[[:space:]]+(-[[:alpha:]]*[[:space:]]+)*-i|sed -i differs between GNU and BSD'
  '(^|[^[:alnum:]_])(stat|date)[[:space:]]+-[cd]|GNU stat/date option'
  '(^|[^[:alnum:]_])find[[:space:]].*-printf|GNU find -printf'
  '--(sort|printf|null-data|zero)([^[:alnum:]-]|$)|GNU-only long option'
  '(^|[^[:alnum:]_.-])jq([^[:alnum:]_-]|$)|jq is not there before Nix'
  '(^|[^[:alnum:]_.-])python3?([^[:alnum:]_-]|$)|python is not there before Nix'
)
for entry in "${forbidden[@]}"; do
  pattern=${entry%|*}
  reason=${entry##*|}
  if matches=$(grep -nE -e "$pattern" <<<"$code"); then
    ds_fail "template/bootstrap.sh uses a non-portable construct ($reason): $matches"
  fi
done
# sha256sum is not on macOS and timeout is not either: both have fallbacks.
assert_contains "$code" "shasum -a 256"
assert_contains "$code" "command -v timeout"
