#!/usr/bin/env bash
# Regenerates template/bootstrap.sh, the instance stage-0 bootstrap, from
# the stage-0 body of cli/commands/preflight.sh and cli/lib/stage0.sh.
#
# Usage: tools/gen-stage0.sh [--check] [--root DIR]
#
# The template is, byte for byte: a fixed header (shebang, description,
# `set -Eeuo pipefail`), the lines between the "# dotsteward:stage0:begin"
# and "# dotsteward:stage0:end" markers of cli/commands/preflight.sh (each
# marker exactly once, begin first), a blank line, cli/lib/stage0.sh without
# its first-line "# shellcheck shell=bash" directive, a blank line and
# `stage0_main "$@"`. Mode 0755.
#
# DIR is the framework checkout (default: the one holding this script).
# Without --check the file is written (atomically) when its bytes or mode
# change. --check only compares and exits 1 when the file is missing,
# stale or not executable (checks.x86_64-linux.stage0-generated runs it).
set -Eeuo pipefail

script_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
# shellcheck source=cli/lib/lib.sh
source "$script_root/cli/lib/lib.sh"

usage() {
  sed -n '6s/^# \{0,1\}//p' "${BASH_SOURCE[0]}"
}

check=0
root=$script_root
while (($#)); do
  case $1 in
    --check)
      check=1
      shift
      ;;
    --root)
      (($# >= 2)) || die "--root requires a directory"
      root=$2
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *) die "unknown option: $1 ($(usage))" ;;
  esac
done
[[ -d $root ]] || die "no such directory: $root"

preflight=$root/cli/commands/preflight.sh
library=$root/cli/lib/stage0.sh
target=$root/template/bootstrap.sh
[[ -f $preflight ]] || die "missing cli/commands/preflight.sh in $root"
[[ -f $library ]] || die "missing cli/lib/stage0.sh in $root"

begin='# dotsteward:stage0:begin'
end='# dotsteward:stage0:end'
markers=$(grep -n -x -e "$begin" -e "$end" "$preflight" || true)
begin_line=${markers%%:*}
end_line=${markers##*$'\n'}
end_line=${end_line%%:*}
if [[ $markers != "$begin_line:$begin"$'\n'"$end_line:$end" ]] || ((begin_line >= end_line)); then
  die "cli/commands/preflight.sh: expected one '$begin' line followed by one '$end' line"
fi

tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/dotsteward-stage0.XXXXXX")
trap 'cleanup_temp_dir "$tmp_dir"' EXIT
rendered=$tmp_dir/bootstrap.sh
{
  cat <<'EOF'
#!/usr/bin/env bash
# dotsteward stage-0 bootstrap: prepares a fresh machine for this instance
# and hands over to `dotsteward bootstrap --stage 1`.
#
# Generated by tools/gen-stage0.sh from the stage-0 body of
# cli/commands/preflight.sh and cli/lib/stage0.sh; do not edit. Instances
# keep this file byte-identical to their pinned framework's
# template/bootstrap.sh (`dotsteward static` checks it; framework upgrades
# refresh it).
#
# Usage: ./bootstrap.sh --profile PROFILE
#        ./bootstrap.sh --install-nix-only
#
# Runs before Nix: with the macOS /bin/bash (3.2) and BSD tools as well as
# on Ubuntu, without jq.
set -Eeuo pipefail

EOF
  sed -n "$((begin_line + 1)),$((end_line - 1))p" "$preflight"
  printf '\n'
  sed '1{/^# shellcheck shell=bash$/d;}' "$library"
  printf '\nstage0_main "$@"\n'
} >"$rendered"
chmod 0755 "$rendered"

if ((check)); then
  [[ -f $target ]] || die "template/bootstrap.sh is missing; run tools/gen-stage0.sh"
  cmp -s -- "$rendered" "$target" || die "template/bootstrap.sh is stale; run tools/gen-stage0.sh"
  [[ -x $target ]] || die "template/bootstrap.sh is not executable; run tools/gen-stage0.sh"
  log "template/bootstrap.sh is up to date"
  exit 0
fi

if [[ -f $target && -x $target ]] && cmp -s -- "$rendered" "$target"; then
  log "template/bootstrap.sh is up to date"
  exit 0
fi
mkdir -p -- "$root/template"
staged=$(mktemp "$root/template/.bootstrap.sh.XXXXXX")
cat -- "$rendered" >"$staged"
chmod 0755 -- "$staged"
mv -f -- "$staged" "$target"
log "wrote template/bootstrap.sh"
