#!/usr/bin/env bash
# Regenerates the generated user documentation: docs/cli.md, the command
# reference built from the help of every command, and docs/catalog.md with
# one docs/components/<name>.md per catalog component, built from the
# component directories.
#
# Usage: tools/gen-docs.sh [--check] [--root DIR]
#
# DIR (default: the framework checkout holding this script) needs
# cli/dotsteward, cli/commands/*.sh and modules/components/*/README.md.
# docs/cli.md has one section per command file, in name order, with the
# command's "# summary:" line and its `--help` output; an argparse command
# adds the help of each subcommand its "positional arguments" list names.
# A component document holds the H1 of the component README, its first
# paragraph and links to the component files; docs/catalog.md lists the
# components with the same paragraph.
#
# Help text is wrapped by Python's argparse, which wraps differently across
# Python versions, so docs/cli.md is compared with its whitespace collapsed:
# a file that differs only in whitespace counts as fresh and is not
# rewritten. The other files are compared byte for byte.
#
# Without --check the stale files are written (atomically) and the
# documents of removed components deleted. --check only compares, names
# every stale, missing or extra file on standard error and exits 1.
# shellcheck disable=SC2016 # Markdown with literal backticks is printed on purpose
set -Eeuo pipefail

script_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)

usage() {
  sed -n '7s/^# \{0,1\}//p' "${BASH_SOURCE[0]}"
}

die() {
  printf '[gen-docs] ERROR: %s\n' "$*" >&2
  exit 1
}

check=0
root=$script_root
while (($#)); do
  case $1 in
    --check)
      check=1
      shift
      ;;
    --root)
      (($# >= 2)) || die "--root requires a directory"
      root=$(cd "$2" && pwd -P) || die "no such directory: $2"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *) die "unknown argument: $1 ($(usage))" ;;
  esac
done
[[ -x $root/cli/dotsteward && -d $root/cli/commands ]] || die "$root has no cli/dotsteward"
[[ -d $root/modules/components ]] || die "$root has no modules/components"

# Help text is rendered for an 80-column terminal without colour, with no
# instance selected.
export COLUMNS=80 NO_COLOR=1 PYTHON_COLORS=0
unset DOTSTEWARD_INSTANCE

work=$(mktemp -d "${TMPDIR:-/tmp}/dotsteward-gen-docs.XXXXXX")
trap 'rm -rf -- "$work"' EXIT
mkdir -p "$work/docs/components"

# help_of ARG...: `dotsteward ARG... --help` without leading and trailing
# blank lines or trailing whitespace.
help_of() {
  local text
  text=$(cd "$root" && "$root/cli/dotsteward" "$@" --help 2>&1) ||
    die "dotsteward $* --help failed: $text"
  printf '%s\n' "$text" | sed 's/[[:space:]]*$//' | awk '
    NF { started = 1 }
    started { lines[++n] = $0; if (NF) last = n }
    END { for (i = 1; i <= last; i++) print lines[i] }'
}

# subcommands_of HELP: the names an argparse "positional arguments" list
# gives, one per line.
subcommands_of() {
  printf '%s\n' "$1" | awk '
    /^positional arguments:/ { block = 1; next }
    block && /^[^ ]/ { block = 0 }
    block && match($0, /^    [a-z][a-z-]*( |$)/) {
      word = substr($0, 5, RLENGTH - 4); sub(/ $/, "", word); print word
    }'
}

summary_of() {
  sed -n 's/^# summary: //p' "$root/cli/commands/$1.sh" | head -n 1
}

mapfile -t commands < <(find "$root/cli/commands" -maxdepth 1 -type f -name '*.sh' -printf '%f\n' |
  sed 's/\.sh$//' | LC_ALL=C sort)
mapfile -t components < <(find "$root/modules/components" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' |
  LC_ALL=C sort)

render_cli() {
  local name summary help sub
  cat <<'MD'
# Command line reference

<!-- Generated by tools/gen-docs.sh from the help of every command; do not edit. -->

This page reproduces the help of every `dotsteward` command. To change it,
edit the help text in `cli/commands/` and run `tools/gen-docs.sh`.

## Entry points

| Where | How to run a command |
| --- | --- |
| In an instance | `./.dotsteward/cli.sh <command>`: the CLI pinned by the instance's `flake.lock`, built once per lock and cached. The wrappers `./rebuild.sh`, `./rollback.sh` and `./update.sh` call it for you. |
| Anywhere with Nix | `nix run github:arda-tuz/dotsteward -- <command>`: the newest release. Inside an instance prefer the pinned launcher. |
| In a framework checkout | `./cli/dotsteward <command>` |

## Global options

```text
dotsteward [--instance DIR] <command> [ARG...]
dotsteward --help
```

- `--instance DIR`: the instance to act on. Without it the CLI uses
  `DOTSTEWARD_INSTANCE`, then the nearest `workstation.toml` above the
  working directory. `version`, `scan`, `init` and `--help` need no instance.
- `--help`: the list of commands with their summaries.
  `dotsteward <command> --help` prints the help reproduced below.

## Output

Progress lines go to standard output as `[dotsteward] ...`; warnings and
errors go to standard error as `[dotsteward] WARNING: ...` and
`[dotsteward] ERROR: ...`. The pins and settings engines keep their own
`[pins]` and `[local-maintained-files]` prefixes. With `--json` a command
prints exactly one JSON document on standard output. The exit status of
every command is listed in [exit-codes.md](exit-codes.md).

## Environment

| Variable | Effect |
| --- | --- |
| `DOTSTEWARD_INSTANCE` | The instance directory, like `--instance`. |
| `DOTSTEWARD_STATE_ROOT` | The root of the machine records, instead of `state.root`. |
| `DOTSTEWARD_NIX_MAX_JOBS`, `DOTSTEWARD_NIX_CORES` | The Nix parallelism of the gate, instead of `gate.nix_max_jobs` and `gate.nix_cores` or the values derived from the machine. |
| `DOTSTEWARD_MEMORY_MIB`, `DOTSTEWARD_CPU_COUNT` | The memory (MiB) and CPU count the derived Nix parallelism of the gate reads, instead of the machine's. |
| `DOTSTEWARD_MIN_FREE_GB` | The free space the gate requires in `/nix/store`, instead of `gate.min_free_gib`. |
| `DOTSTEWARD_CACHE_URL` | The binary cache the gate probes, instead of `gate.cache_url`. |
| `DOTSTEWARD_FRAMEWORK_OVERRIDE` | The framework flake reference of `--framework-override`. |
| `DOTSTEWARD_ASSUME_YES` | `1` answers installer and package manager confirmations; meant for CI runners only. |
| `DOTSTEWARD_CLI` | A CLI that `.dotsteward/cli.sh` runs instead of building the pinned one. |

## Commands

| Command | Summary |
| --- | --- |
MD
  for name in "${commands[@]}"; do
    printf '| [`%s`](#%s) | %s |\n' "$name" "$name" "$(summary_of "$name")"
  done
  for name in "${commands[@]}"; do
    summary=$(summary_of "$name")
    help=$(help_of "$name")
    printf '\n## `%s`\n\n' "$name"
    [[ -z $summary ]] || printf '%s.\n\n' "${summary%.}"
    printf '```text\n%s\n```\n' "$help"
    while IFS= read -r sub; do
      [[ -n $sub ]] || continue
      printf '\n### `%s %s`\n\n```text\n%s\n```\n' "$name" "$sub" "$(help_of "$name" "$sub")"
    done < <(subcommands_of "$help")
  done
}

# component_title NAME and component_summary NAME: the H1 of the component
# README and its first paragraph, joined into one line.
component_title() {
  sed -n '1s/^# //p' "$root/modules/components/$1/README.md"
}

component_summary() {
  awk 'NR == 1 { next } NF { started = 1; printf "%s%s", (n++ ? " " : ""), $0; next }
       started { exit }' "$root/modules/components/$1/README.md"
}

render_component() {
  local name=$1 dir="../../modules/components/$1" file
  [[ -f $root/modules/components/$name/README.md ]] || die "modules/components/$name has no README.md"
  printf '# %s\n\n' "$(component_title "$name")"
  printf '<!-- Generated by tools/gen-docs.sh from modules/components/%s; do not edit. -->\n\n' "$name"
  printf '%s\n\n' "$(component_summary "$name")"
  printf 'The component lives in [`modules/components/%s`](%s/):\n\n' "$name" "$dir"
  printf -- '- [README.md](%s/README.md): what it installs, its options and its settings.\n' "$dir"
  for file in maintenance.md default.nix seed.json; do
    [[ -f $root/modules/components/$name/$file ]] || continue
    case $file in
      maintenance.md) printf -- '- [maintenance.md](%s/maintenance.md): its pins and how `dotsteward-update` refreshes them.\n' "$dir" ;;
      default.nix) printf -- '- [default.nix](%s/default.nix): the Home Manager module that fills the component contract.\n' "$dir" ;;
      seed.json) printf -- '- [seed.json](%s/seed.json): the flake inputs and lock entries an instance starts with when it enables the component.\n' "$dir" ;;
    esac
  done
  printf '\nSee the [catalog](../catalog.md) for the other components.\n'
}

render_catalog() {
  local name
  cat <<'MD'
# Catalog

<!-- Generated by tools/gen-docs.sh from modules/components; do not edit. -->

The framework ships the components below. Enable one with a
`[components.<name>]` table in `workstation.toml` (see
[workstation-toml.md](workstation-toml.md)); `dotsteward init --components`
takes the same names. Anything else is a private component of your instance,
written against the same contract (see [concepts.md](concepts.md)).

| Component | What it provides |
| --- | --- |
MD
  for name in "${components[@]}"; do
    printf '| [`%s`](components/%s.md) | %s |\n' "$name" "$name" "$(component_summary "$name")"
  done
}

render_cli >"$work/docs/cli.md"
render_catalog >"$work/docs/catalog.md"
for name in "${components[@]}"; do
  render_component "$name" >"$work/docs/components/$name.md"
done

squeeze() {
  tr -s '[:space:]' ' ' <"$1"
}

# same GENERATED PATH: true when PATH (relative to root) is fresh.
same() {
  local generated=$1 path=$2
  [[ -f $root/$path ]] || return 1
  if [[ $path == docs/cli.md ]]; then
    [[ $(squeeze "$generated") == "$(squeeze "$root/$path")" ]]
  else
    cmp -s -- "$generated" "$root/$path"
  fi
}

stale=()
while IFS= read -r path; do
  same "$work/$path" "$path" || stale+=("$path")
done < <(cd "$work" && find docs -type f | LC_ALL=C sort)
extra=()
if [[ -d $root/docs/components ]]; then
  while IFS= read -r path; do
    [[ -f $work/$path ]] || extra+=("$path")
  done < <(cd "$root" && find docs/components -type f -name '*.md' | LC_ALL=C sort)
fi

if ((check)); then
  for path in "${stale[@]}"; do
    printf '[gen-docs] stale or missing: %s (run tools/gen-docs.sh)\n' "$path" >&2
  done
  for path in "${extra[@]}"; do
    printf '[gen-docs] not generated: %s (run tools/gen-docs.sh)\n' "$path" >&2
  done
  ((${#stale[@]} + ${#extra[@]} == 0))
  exit
fi

for path in "${stale[@]}"; do
  mkdir -p "$(dirname "$root/$path")"
  cp -- "$work/$path" "$root/$path.tmp.$$"
  chmod 0644 "$root/$path.tmp.$$"
  mv -f -- "$root/$path.tmp.$$" "$root/$path"
  printf '[gen-docs] wrote %s\n' "$path"
done
for path in "${extra[@]}"; do
  rm -f -- "$root/$path"
  printf '[gen-docs] removed %s\n' "$path"
done
